name = "purescript-cloudflare-workers"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-04-10"

[build.upload]
format = "modules"
dir = "dist"
main = "index.mjs"

[[kv_namespaces]]
binding = "testkv"
preview_id = ""
id = ""